### ISSUE TITLE
Cannot Clone repository No Permissions for Alljoyn

### ISSUE THREAD

**Issue by rickblair** [devicehive/IoT-framework#27]
I cannot follow the directions to clone the repository.  

git clone --recursive https://github.com/devicehive/IoT-framework.git
Cloning into 'IoT-framework'...
remote: Counting objects: 2311, done.
remote: Total 2311 (delta 0), reused 0 (delta 0), pack-reused 2311
Receiving objects: 100% (2311/2311), 1.87 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (1332/1332), done.
Checking connectivity... done.
Submodule 'devicehive-alljoyn/alljoyn' (git@github.com:devicehive/alljoyn.git) registered for path 'devicehive-alljoyn/alljoyn'
Cloning into 'devicehive-alljoyn/alljoyn'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:devicehive/alljoyn.git' into submodule path 'devicehive-alljoyn/alljoyn' failed

**Comment by demon-xxi** [comment]
Hi @rickblair, 

Do you have your SSH key setup for GitHub? 
I see that submodule link to devicehive/alljoyn repo is using ssh path git@github.com:devicehive/alljoyn.git
And it is trying to clone that way. But for that to work you need ssh key to be configured.

You  can also test ssh by cloning that repo alone:
git clone --recursive git@github.com:devicehive/alljoyn.git

Most likely give you access error until you configure ssh.

**Comment by rickblair** [comment]
thanks!

Perhaps that should be in the documentation.

**Comment by devrn** [comment]
May be let's just change 'git' to 'https' in submodule?

**Comment by demon-xxi** [comment]
We'll check if that works. For now used ssh  for easier push/pull in submodules. But since submodule is now mostly ready and needs less changes. that may be better.
Too bad that git does not provide that flexibility by default.

**Comment by demon-xxi** [comment]
I've updated instructions for now to use ssh. Not a solution but will be more obvious about this issue until we migrate submodules to https as well.

**Comment by demon-xxi** [comment]
Thank you for the issue report. Can we close issue for now?

**Comment by rickblair** [comment]
Sure.

Thanks for the quick turnaround.
